{{- range .Values.applications }}
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener
  namespace: {{ .projectName }}
spec:
  serviceAccountName: pipeline
  triggers:
    - name: {{ .appName}}-trigger
      interceptors:
        - ref:
            name: "cel"
          params:
            - name: "filter"
              value: "body.html_url == {{ .gitURL }}"
      bindings:
        - kind: TriggerBinding
          ref: {{ .appName}}-triggerbinding
      template:
        ref: {{ .appName}}-triggertemplate
{{- end}}