{{- range .Values.applications }}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .appName}}-pipeline
  namespace: {{ .projectName }}
spec:
  params:
    - description: URL of the git repo
      name: GIT_REPO
      type: string
    - default: main
      description: Revision/Branch of git repo
      name: GIT_REV
      type: string
    - description: Name and tag of the new created image
      name: IMAGE
      type: string
  tasks:
  - name: checkout-git
    params:
      - name: url
        value: $(params.GIT_REPO)
      - name: revision
        value: $(params.GIT_REV)
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
      - name: output
        workspace: shared-data
  - name: container-build-and-push
    params:
      - name: IMAGE
        value: $(params.IMAGE)
    runAfter:
      - checkout-git
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
      - name: source
        workspace: shared-data
  workspaces:
    - description: This workspace will receive the cloned git repo.
      name: shared-data
{{- end}}