{{- range .Values.applications }}
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .appName}}-pipeline
spec:
  params:
    - description: URL of the git repo
      name: GIT_REPO
      type: string
    - default: main
      description: Revision/Branch of git repo
      name: GIT_REV
      type: string
  tasks:
    - name: checkout-scm
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REV)
      taskRef:
        kind: ClusterTask
        name: poc-git-clone-clustertask
      workspaces:
        - name: output
          workspace: shared-data
  workspaces:
    - description: This workspace will receive the cloned git repo.
      name: shared-data
{{- end}}