{{- range .Values.applications }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .appName}}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
{{- end}}