{{- range .Values.applications }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .appName}}-pvc
  {{- if .projectname }}
  namespace: {{ .projectname }}
  {{-- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
{{- end}}