kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Values.workspace.pvcName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
