{{- range .Values.applications }}
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: {{ .appName}}-triggerbinding
  {{- if .projectname }}
  namespace: {{ .projectname }}
  {{-- end }}
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: imageurl
      value: {{ .imageURL}}
{{- end}}